### ISSUE TITLE
Wrong paths to media files

### ISSUE THREAD

**Issue by slabousAndrey** [serhiibravo/Bouncy#1]
**Can't resolve media files**
![Screenshot from 2019-07-20 10-13-45](https://user-images.githubusercontent.com/40362626/61575655-1a73d480-aad7-11e9-8803-03616dc493ab.png)

**My steps to reproduce**:
1. clone git repository via GitBash command `git clone https://github.com/serhiibravo/Bouncy`
2. install all dependencies via NodeJS command `yarn`
3. run the project via NodeJS command `yarn run dev`

**Comment by serhiibravo** [comment]
- Added the root directory in the paths to the pictures.
Please check this patch on your

**Comment by slabousAndrey** [comment]
@serhiibravo
working, well done
